spring:
  application:
    name: currency-exchange
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

server:
  port: 8000


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 3
        waitDuration: 3s
        enable-exponential-backoff: true
  ratelimiter:
    instances:
      default:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
#resilience4j.retry.instances.sample-api.maxRetryAttempts=5 #OLD
